### ISSUE TITLE
SentinelOne Virus Alert

### ISSUE THREAD

**Issue by mbcomptech** [Romanitho/WingetIntunePackager#13]
Hello, FYI S1 is detecting this as a virus due to "On-Write Static AI - Suspicious" engine.

Virus Total doesn't like it: https://www.virustotal.com/gui/file/70cbcfd413e0bb19bb422fcbee6642af1c333a37ac5ae1cef9e0eb60db1dc649

**Comment by ee61re** [comment]
FYI, my SOC had a look, and told me:

The code itself is not signed and this will always be flagged, we aren't seeing much further information from the agent as a result but checking with VT we can see 18 other vendors flagging the application as malicious. 

One other element is that one of the IP addresses contacted ([20.99.184.37](https://www.virustotal.com/gui/ip-address/20.99.184.37)) has been used as a C2 server and also used to deliver OxtaRAT. 

We did run this in the lab and once active there are a lot of elements that would also trigger a detection such as suspected kerberoasting attack, obfuscated PowerShell commands and Non-powershell process loaded powershell module.

**Comment by Romanitho** [comment]
sure, the code is not signed. It costs... And the EXE itself is generated with PS2EXE... It is just created to simplify things.
I agree, regarding security (as already said) use the PowerShell script instead of EXE. And of course, read the script first to understand what it does before running it.
Hope it helps.

**Comment by Romanitho** [comment]
Closed due to inactivity
